import { CategoriesSelector, Navbar } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { store } from "@/redux/store";
import { getAvailableCategories } from "@/redux/reducers/categoriesReducer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className='sm:w-10/12 mx-auto overflow-x-hidden'>
          <CategoriesSelector />
          {children}
        </div>
      </body>
    </html>
  );
}
