export { default as Navbar } from "./Navbar/Navbar";
export { default as CategoriesSelector } from "./CategoriesSelector/CategoriesSelector";
export { default as ProductResults } from "./ProductResults/ProductsResults";
export { default as Packages } from "./Packages/Packages";
export { default as Checkout } from "./Checkout/Checkout";
export { default as NoResults } from "./NoResults/NoResults";
export { default as Search } from "./Search/Search";
export { default as Orders } from "./Orders/Orders";
// export { default as Category } from "./Categories/Category/Category";
// export { default as Categories } from "./Categories/Categories";
// export { default as LoginSignUp  } from "./LoginSignUp/LoginSignUp";
// export { default as Checkout } from "./Checkout/Checkout";
// export { default as Footer } from "./Footer/Footer";